import type {
  MockContextProfile,
  MockContextProfileOverrides,
  MockContextScenario,
} from "@city-wallet/contracts";

export type ScenarioPreset = {
  id: MockContextScenario;
  label: string;
  description: string;
  enabledSources: Record<string, boolean>;
  signalPayloads: MockContextProfile["signalPayloads"];
  // Transient overrides applied to the user's profile + context snapshot
  // when this scenario (or a profile derived from it) is active. Lets a
  // "tourist" scenario actually widen the walking radius, etc.
  profileOverrides?: MockContextProfileOverrides;
};

export const scenarioPresets: ScenarioPreset[] = [
  {
    id: "heavy_workday_30min_gap_cold",
    label: "Heavy workday, 30-min gap, cold",
    description: "Stressed, short gap before next meeting, cold weather mood, prefers quick warm break.",
    profileOverrides: {
      walkingToleranceMeters: 350,
      maxBundleStops: 1,
      maxOffersPerHour: 1,
      rewardPreference: "cashback",
      privacyMode: "high",
      declaredIntent: "warm_quick_break",
      availableMinutes: 30,
    },
    enabledSources: {
      calendar: true,
      fitness: true,
      mobility: true,
      mood: true,
      payment_preference: true,
      device_attention: true,
      dietary: true,
      social: false,
      transit: false,
      local_events: false,
    },
    signalPayloads: {
      calendar: {
        freeWindowMinutes: 30,
        nextEventInMinutes: 35,
        nextEventType: "work",
        dayLoad: "heavy",
        hasHardStop: true,
        locationHint: "nearby",
      },
      fitness: {
        sleepQuality: "okay",
        energyLevel: "low",
        recentWorkout: false,
        recoveryNeed: "medium",
        activityLoadToday: "low",
      },
      mobility: { movementState: "walking_slowly", dwellPattern: "browsing", familiarity: "familiar_area" },
      mood: { moodState: "stressed", confidence: 0.8, basis: ["heavy_calendar", "low_energy"] },
      payment_preference: {
        rewardPreference: "convenience",
        priceSensitivity: "medium",
        categoryAffinities: ["cafe", "bakery"],
        recentCategoryAvoidance: [],
      },
      device_attention: {
        screenActive: true,
        focusMode: false,
        batteryLevel: "medium",
        headphonesConnected: false,
        notificationTolerance: "low",
      },
      dietary: { dietaryHints: [], avoidFoodCategories: [], preferredFoodStyle: "hearty" },
    },
  },
  {
    id: "post_workout_healthy_refuel",
    label: "Post-workout, healthy refuel",
    description: "Just finished a workout, looking for healthy quick fuel.",
    profileOverrides: {
      walkingToleranceMeters: 800,
      maxBundleStops: 2,
      maxOffersPerHour: 2,
      rewardPreference: "discount",
      privacyMode: "medium",
      declaredIntent: "healthy_refuel",
      availableMinutes: 60,
    },
    enabledSources: {
      calendar: true,
      fitness: true,
      mobility: true,
      mood: true,
      payment_preference: true,
      dietary: true,
      device_attention: true,
      social: false,
      transit: false,
      local_events: false,
    },
    signalPayloads: {
      calendar: { freeWindowMinutes: 90, dayLoad: "light", hasHardStop: false, locationHint: "nearby" },
      fitness: {
        sleepQuality: "good",
        energyLevel: "medium",
        recentWorkout: true,
        recoveryNeed: "high",
        activityLoadToday: "high",
      },
      mobility: { movementState: "walking_fast", dwellPattern: "browsing", familiarity: "familiar_area" },
      mood: { moodState: "calm", confidence: 0.7, basis: ["recent_workout", "good_sleep"] },
      payment_preference: {
        rewardPreference: "discovery",
        priceSensitivity: "medium",
        categoryAffinities: ["cafe", "grocery"],
        recentCategoryAvoidance: [],
      },
      dietary: {
        dietaryHints: ["vegetarian"],
        avoidFoodCategories: ["fried_food"],
        preferredFoodStyle: "healthy",
      },
      device_attention: {
        screenActive: true,
        focusMode: false,
        batteryLevel: "high",
        headphonesConnected: true,
        notificationTolerance: "high",
      },
    },
  },
  {
    id: "date_night_soon",
    label: "Date night soon",
    description: "Evening plans, looking for something thoughtful or premium.",
    profileOverrides: {
      walkingToleranceMeters: 1_200,
      maxBundleStops: 2,
      maxOffersPerHour: 1,
      rewardPreference: "discount",
      privacyMode: "medium",
      declaredIntent: "premium_treat",
      availableMinutes: 75,
    },
    enabledSources: {
      calendar: true,
      mood: true,
      social: true,
      payment_preference: true,
      mobility: true,
      device_attention: true,
      dietary: true,
      fitness: false,
      transit: false,
      local_events: false,
    },
    signalPayloads: {
      calendar: {
        freeWindowMinutes: 75,
        nextEventInMinutes: 90,
        nextEventType: "social",
        dayLoad: "medium",
        hasHardStop: true,
        locationHint: "nearby",
      },
      mood: { moodState: "celebratory", confidence: 0.8, basis: ["upcoming_social_event"] },
      social: { socialMode: "date", groupSize: 2, nextSocialCommitmentInMinutes: 90 },
      payment_preference: {
        rewardPreference: "premium",
        priceSensitivity: "low",
        categoryAffinities: ["flower_shop", "bakery", "gift_shop"],
        recentCategoryAvoidance: [],
      },
      mobility: { movementState: "walking_slowly", dwellPattern: "browsing", familiarity: "familiar_area" },
      device_attention: {
        screenActive: true,
        focusMode: false,
        batteryLevel: "medium",
        headphonesConnected: false,
        notificationTolerance: "high",
      },
      dietary: { dietaryHints: [], avoidFoodCategories: [], preferredFoodStyle: "sweet" },
    },
  },
  {
    id: "waiting_for_train",
    label: "Waiting for delayed train",
    description: "At station, train delayed; quick local options near platform.",
    profileOverrides: {
      walkingToleranceMeters: 250,
      maxBundleStops: 1,
      maxOffersPerHour: 1,
      rewardPreference: "cashback",
      privacyMode: "high",
      declaredIntent: "quick_grab",
      availableMinutes: 25,
    },
    enabledSources: {
      calendar: true,
      transit: true,
      mood: true,
      mobility: true,
      payment_preference: true,
      device_attention: true,
      dietary: true,
      fitness: false,
      social: false,
      local_events: false,
    },
    signalPayloads: {
      calendar: { freeWindowMinutes: 25, dayLoad: "medium", hasHardStop: true, locationHint: "nearby" },
      transit: { transitState: "delayed_train", departureInMinutes: 25, delayMinutes: 15 },
      mood: { moodState: "stressed", confidence: 0.6, basis: ["delay"] },
      mobility: { movementState: "stationary", dwellPattern: "waiting", familiarity: "unfamiliar_area" },
      payment_preference: {
        rewardPreference: "convenience",
        priceSensitivity: "medium",
        categoryAffinities: ["cafe", "bakery"],
        recentCategoryAvoidance: [],
      },
      device_attention: {
        screenActive: true,
        focusMode: false,
        batteryLevel: "low",
        headphonesConnected: true,
        notificationTolerance: "medium",
      },
      dietary: { dietaryHints: [], avoidFoodCategories: [], preferredFoodStyle: "light" },
    },
  },
  {
    id: "tourist_exploring",
    label: "Tourist exploring",
    description: "Unfamiliar area, exploration mood, open to local discovery.",
    profileOverrides: {
      walkingToleranceMeters: 2_000,
      maxBundleStops: 3,
      maxOffersPerHour: 2,
      rewardPreference: "either",
      privacyMode: "low",
      declaredIntent: "local_discovery",
      availableMinutes: 180,
    },
    enabledSources: {
      mobility: true,
      mood: true,
      payment_preference: true,
      device_attention: true,
      calendar: true,
      dietary: true,
      fitness: false,
      social: false,
      transit: false,
      local_events: true,
    },
    signalPayloads: {
      calendar: { freeWindowMinutes: 180, dayLoad: "light", hasHardStop: false, locationHint: "nearby" },
      mobility: { movementState: "walking_slowly", dwellPattern: "browsing", familiarity: "tourist_mode" },
      mood: { moodState: "social", confidence: 0.7, basis: ["unfamiliar_area"] },
      payment_preference: {
        rewardPreference: "discovery",
        priceSensitivity: "low",
        categoryAffinities: ["museum", "gallery", "gift_shop", "bookshop"],
        recentCategoryAvoidance: [],
      },
      device_attention: {
        screenActive: true,
        focusMode: false,
        batteryLevel: "high",
        headphonesConnected: false,
        notificationTolerance: "high",
      },
      local_events: { nearbyEventType: "museum_event", eventWindow: "during_event", crowdLevel: "medium" },
      dietary: { dietaryHints: [], avoidFoodCategories: [], preferredFoodStyle: "unknown" },
    },
  },
  {
    id: "low_energy_poor_sleep",
    label: "Low energy after poor sleep",
    description: "Exhausted, prefers comfort food, low attention.",
    profileOverrides: {
      walkingToleranceMeters: 400,
      maxBundleStops: 1,
      maxOffersPerHour: 1,
      rewardPreference: "cashback",
      privacyMode: "high",
      declaredIntent: "comfort_break",
      availableMinutes: 60,
    },
    enabledSources: {
      fitness: true,
      mood: true,
      mobility: true,
      payment_preference: true,
      device_attention: true,
      calendar: true,
      dietary: true,
      social: false,
      transit: false,
      local_events: false,
    },
    signalPayloads: {
      calendar: { freeWindowMinutes: 60, dayLoad: "medium", hasHardStop: false, locationHint: "nearby" },
      fitness: {
        sleepQuality: "poor",
        energyLevel: "low",
        recentWorkout: false,
        recoveryNeed: "high",
        activityLoadToday: "low",
      },
      mood: { moodState: "tired", confidence: 0.85, basis: ["poor_sleep"] },
      mobility: { movementState: "stationary", dwellPattern: "browsing", familiarity: "familiar_area" },
      payment_preference: {
        rewardPreference: "convenience",
        priceSensitivity: "high",
        categoryAffinities: ["cafe", "bakery"],
        recentCategoryAvoidance: [],
      },
      device_attention: {
        screenActive: false,
        focusMode: true,
        batteryLevel: "medium",
        headphonesConnected: false,
        notificationTolerance: "low",
      },
      dietary: { dietaryHints: [], avoidFoodCategories: [], preferredFoodStyle: "hearty" },
    },
  },
  {
    id: "social_meetup",
    label: "Social meetup",
    description: "Meeting friends, looking for shareable experiences.",
    profileOverrides: {
      walkingToleranceMeters: 1_200,
      maxBundleStops: 3,
      maxOffersPerHour: 2,
      rewardPreference: "discount",
      privacyMode: "medium",
      declaredIntent: "social_share",
      availableMinutes: 120,
    },
    enabledSources: {
      calendar: true,
      social: true,
      mood: true,
      mobility: true,
      payment_preference: true,
      device_attention: true,
      dietary: true,
      fitness: false,
      transit: false,
      local_events: false,
    },
    signalPayloads: {
      calendar: {
        freeWindowMinutes: 120,
        nextEventInMinutes: 60,
        nextEventType: "social",
        dayLoad: "light",
        hasHardStop: true,
        locationHint: "nearby",
      },
      social: { socialMode: "friend_meetup", groupSize: 3, nextSocialCommitmentInMinutes: 60 },
      mood: { moodState: "social", confidence: 0.8, basis: ["upcoming_meetup"] },
      mobility: { movementState: "walking_slowly", dwellPattern: "browsing", familiarity: "familiar_area" },
      payment_preference: {
        rewardPreference: "discovery",
        priceSensitivity: "medium",
        categoryAffinities: ["cafe", "bakery", "restaurant"],
        recentCategoryAvoidance: [],
      },
      device_attention: {
        screenActive: true,
        focusMode: false,
        batteryLevel: "medium",
        headphonesConnected: false,
        notificationTolerance: "high",
      },
      dietary: { dietaryHints: [], avoidFoodCategories: [], preferredFoodStyle: "light" },
    },
  },
  {
    id: "budget_conscious_errand_run",
    label: "Budget-conscious errand run",
    description: "Running errands, value-focused, prefers cashback.",
    profileOverrides: {
      walkingToleranceMeters: 800,
      maxBundleStops: 3,
      maxOffersPerHour: 2,
      rewardPreference: "cashback",
      privacyMode: "medium",
      declaredIntent: "errand_run",
      availableMinutes: 90,
    },
    enabledSources: {
      calendar: true,
      mobility: true,
      payment_preference: true,
      device_attention: true,
      mood: true,
      dietary: true,
      fitness: false,
      social: false,
      transit: false,
      local_events: false,
    },
    signalPayloads: {
      calendar: { freeWindowMinutes: 90, dayLoad: "medium", hasHardStop: false, locationHint: "nearby" },
      mobility: { movementState: "walking_fast", dwellPattern: "commuting", familiarity: "familiar_area" },
      payment_preference: {
        rewardPreference: "cashback",
        priceSensitivity: "high",
        categoryAffinities: ["grocery", "stationery", "local_retail"],
        recentCategoryAvoidance: [],
      },
      device_attention: {
        screenActive: true,
        focusMode: false,
        batteryLevel: "medium",
        headphonesConnected: false,
        notificationTolerance: "medium",
      },
      mood: { moodState: "focused", confidence: 0.7, basis: ["task_orientation"] },
      dietary: { dietaryHints: [], avoidFoodCategories: [], preferredFoodStyle: "unknown" },
    },
  },
  {
    id: "quiet_focus_break",
    label: "Quiet focus break",
    description: "Looking for a quiet place to work or read.",
    profileOverrides: {
      walkingToleranceMeters: 400,
      maxBundleStops: 1,
      maxOffersPerHour: 1,
      rewardPreference: "discount",
      privacyMode: "high",
      declaredIntent: "quiet_focus",
      availableMinutes: 90,
    },
    enabledSources: {
      calendar: true,
      mood: true,
      device_attention: true,
      payment_preference: true,
      mobility: true,
      dietary: true,
      fitness: false,
      social: false,
      transit: false,
      local_events: false,
    },
    signalPayloads: {
      calendar: { freeWindowMinutes: 90, dayLoad: "medium", hasHardStop: false, locationHint: "nearby" },
      mood: { moodState: "focused", confidence: 0.85, basis: ["device_focus_mode"] },
      device_attention: {
        screenActive: true,
        focusMode: true,
        batteryLevel: "high",
        headphonesConnected: true,
        notificationTolerance: "low",
      },
      payment_preference: {
        rewardPreference: "convenience",
        priceSensitivity: "medium",
        categoryAffinities: ["cafe", "bookshop"],
        recentCategoryAvoidance: [],
      },
      mobility: { movementState: "stationary", dwellPattern: "browsing", familiarity: "familiar_area" },
      dietary: { dietaryHints: [], avoidFoodCategories: [], preferredFoodStyle: "light" },
    },
  },
  {
    id: "gift_on_the_way",
    label: "Gift on the way",
    description: "On the way to a friend, picking up a small gift.",
    profileOverrides: {
      walkingToleranceMeters: 600,
      maxBundleStops: 1,
      maxOffersPerHour: 1,
      rewardPreference: "discount",
      privacyMode: "medium",
      declaredIntent: "quick_gift",
      availableMinutes: 30,
    },
    enabledSources: {
      calendar: true,
      mobility: true,
      payment_preference: true,
      mood: true,
      social: true,
      device_attention: true,
      dietary: true,
      fitness: false,
      transit: false,
      local_events: false,
    },
    signalPayloads: {
      calendar: {
        freeWindowMinutes: 30,
        nextEventInMinutes: 35,
        nextEventType: "social",
        dayLoad: "light",
        hasHardStop: true,
        locationHint: "nearby",
      },
      mobility: { movementState: "walking_fast", dwellPattern: "commuting", familiarity: "familiar_area" },
      payment_preference: {
        rewardPreference: "premium",
        priceSensitivity: "medium",
        categoryAffinities: ["flower_shop", "bakery", "gift_shop", "bookshop"],
        recentCategoryAvoidance: [],
      },
      mood: { moodState: "social", confidence: 0.75, basis: ["pre_social_event"] },
      social: { socialMode: "friend_meetup", groupSize: 2, nextSocialCommitmentInMinutes: 35 },
      device_attention: {
        screenActive: true,
        focusMode: false,
        batteryLevel: "high",
        headphonesConnected: false,
        notificationTolerance: "high",
      },
      dietary: { dietaryHints: [], avoidFoodCategories: [], preferredFoodStyle: "unknown" },
    },
  },
  {
    id: "lunch_break_with_visitor",
    label: "Lunch break + visitor in an hour",
    description:
      "User is taking a lunch break right now AND a friend is arriving in about an hour, so a small gift stop makes sense alongside lunch.",
    profileOverrides: {
      walkingToleranceMeters: 900,
      maxBundleStops: 2,
      maxOffersPerHour: 2,
      rewardPreference: "either",
      privacyMode: "medium",
      declaredIntent: "lunch_break_with_visitor",
      availableMinutes: 55,
    },
    enabledSources: {
      calendar: true,
      mood: true,
      mobility: true,
      payment_preference: true,
      device_attention: true,
      social: true,
      dietary: true,
      fitness: false,
      transit: false,
      local_events: false,
    },
    signalPayloads: {
      calendar: {
        freeWindowMinutes: 55,
        nextEventInMinutes: 60,
        nextEventType: "social",
        dayLoad: "medium",
        hasHardStop: true,
        locationHint: "nearby",
      },
      mood: {
        moodState: "social",
        confidence: 0.8,
        basis: ["scheduled_lunch", "incoming_visitor"],
      },
      mobility: { movementState: "walking_slowly", dwellPattern: "browsing", familiarity: "familiar_area" },
      payment_preference: {
        rewardPreference: "discovery",
        priceSensitivity: "medium",
        categoryAffinities: ["cafe", "restaurant", "bakery", "flower_shop", "gift_shop"],
        recentCategoryAvoidance: [],
      },
      device_attention: {
        screenActive: true,
        focusMode: false,
        batteryLevel: "high",
        headphonesConnected: false,
        notificationTolerance: "high",
      },
      social: {
        socialMode: "friend_visiting",
        groupSize: 2,
        nextSocialCommitmentInMinutes: 60,
        visitorContext: {
          arrivingInMinutes: 60,
          relation: "close_friend",
          suggestedGiftCategories: ["flower_shop", "bakery", "gift_shop", "bookshop"],
        },
      },
      dietary: { dietaryHints: [], avoidFoodCategories: [], preferredFoodStyle: "light" },
    },
  },
];

export function getScenarioPreset(id: MockContextScenario): ScenarioPreset | undefined {
  return scenarioPresets.find((preset) => preset.id === id);
}
